/**
 * Variantes de libellés pour les 60 questions du test.
 * Chaque variante ne change QUE le texte affiché : l'ordre (et donc le
 * mapping vers les états du moi via MAPPING dans index.tsx) reste identique
 * pour les 3 tableaux, question par question.
 */
export type QuestionVariantKey = "default" | "scouts" | "ape";

export const QUESTION_VARIANT_LABELS: Record<QuestionVariantKey, string> = {
  default: "Standard",
  scouts: "Scouts et Guides",
  ape: "Association de Parents d'Élèves",
};

/**
 * Contexte injecté dans les prompts d'analyse IA pour que les exemples
 * concrets (situations, vocabulaire) correspondent au public ayant répondu
 * avec cette variante de questions. `audience` est vide pour "default" (aucun
 * ajout au prompt) ; `examples` et `meetingContext` remplacent des membres de
 * phrase fixes dans analysis-prompts.ts.
 */
export const QUESTION_VARIANT_CONTEXT_PROMPTS: Record<
  QuestionVariantKey,
  { audience: string; examples: string; meetingContext: string }
> = {
  default: {
    audience: "",
    examples: "en réunion, en famille, sous stress",
    meetingContext: "en réunion",
  },
  scouts: {
    audience:
      "Le public ayant répondu est composé de chefs et cheftaines Scouts et Guides, jeunes adultes ayant des responsabilités d'encadrement de jeunes. Adapte TOUS tes exemples concrets à cet univers (camps, veillées, réunions de chefs, activités avec les jeunes, la loi scoute) plutôt qu'à un contexte professionnel classique.",
    examples: "en camp, en réunion de chefs, en veillée, sous stress",
    meetingContext: "en réunion de chefs ou pendant un camp",
  },
  ape: {
    audience:
      "Le public ayant répondu est composé de membres actifs d'une Association de Parents d'Élèves (bureau de l'association, organisation d'événements scolaires). Adapte TOUS tes exemples concrets à cet univers (réunions de bureau, kermesse, sorties scolaires, buvette, relations avec l'école) plutôt qu'à un contexte professionnel classique.",
    examples: "en réunion de bureau, en famille, lors d'un événement scolaire, sous stress",
    meetingContext: "en réunion de bureau ou lors de l'organisation d'un événement",
  },
};

const DEFAULT_QUESTIONS: string[] = [
  "On dit que j'ai du sang froid",
  "J'aime bien rire aux dépens des autres",
  "Je me laisse influencer facilement",
  "Je rends visite aux copains malades",
  "Je sais apprécier les imprévus",
  "J'admets très mal la tricherie",
  "J'aime beaucoup les voyages",
  "Je remonte fréquemment le moral aux copains qui dépriment",
  "Je n'arrive pas en retard pour ne pas me faire remarquer",
  "Je suis souvent en désaccord avec mon entourage",
  "On me trouve logique et rationnel",
  "Il faut respecter les délais",
  "Je ne contredis jamais un supérieur hiérarchique",
  "J'aide sans qu'on me le demande",
  "Je sympathise assez souvent avec des inconnus",
  "Les absences doivent être justifiées",
  "Avant d'effectuer un travail, je réfléchis sur la méthode à suivre",
  "Je suis râleur, contestataire",
  "Je suis organisé dans mon travail",
  "Je repère facilement les défauts des autres",
  "Je dis « oui » alors que je voulais dire « non »",
  "Je prête facilement mes affaires",
  "Quand quelqu'un me plaît je n'hésite pas à le lui dire",
  "J'apprécie la discipline",
  "Quand je suis en colère, on m'entend",
  "Je porte souvent des appréciations sur les gens",
  "Confronté à un échec, je réfléchis calmement",
  "Je préfère donner que recevoir",
  "Dans une situation difficile je garde ma présence d'esprit",
  "Quand il convient d'être en smoking, j'ai tendance à mettre une chemise à fleurs",
  "J'accorde de l'importance à ce qu'on pense de moi",
  "Je n'aime pas partir dans l'inconnu, il faut que ce soit planifié",
  "J'aime à rassurer mon entourage",
  "J'évite de prendre des responsabilités",
  "J'adore taquiner",
  "J'ai tendance à passer beaucoup de temps à aider les autres",
  "Ce n'est pas acceptable de doubler dans les files d'attente",
  "Je prévois les conséquences de mes actions",
  "Je choque souvent par mes propos",
  "Je suis plutôt timide",
  "On me trouve enthousiaste",
  "Je remets mes opinions en questions quand il le faut",
  "Quand je suis content ça se voit",
  "Quand un problème se pose, j'amasse le plus de données possibles pour le résoudre objectivement",
  "J'aime la satire et la dérision",
  "J'ai le souci de ne pas importuner les autres",
  "Je ne cache pas mes émotions",
  "Il est intolérable de faire claquer des pétards dans les cimetières",
  "J'ai l'esprit de contradiction",
  "Ça ne me déplairait pas d'être médecin sans frontières",
  "Je me fais petit devant l'autorité",
  "Il est dommage que certaines valeurs se perdent",
  "Avec moi on ne s'ennuie pas",
  "Dans le doute je sais me documenter",
  "Je suis réputé pour la férocité de mes remarques",
  "Dure est la loi, mais c'est la loi",
  "On me dit que je suis trop bon",
  "J'essaie de ressembler à ce que mes parents voulaient que je fusse",
  "J'ai toujours une histoire, drôle ou pas, à raconter",
  "J'ai tendance à prendre les opprimés sous mon aile",
];

const SCOUTS_QUESTIONS: string[] = [
  "En cas d'imprévu pendant un camp, je garde mon sang-froid",
  "J'aime bien chambrer les autres chefs ou les scouts",
  "Je me laisse facilement convaincre par l'avis du groupe",
  "Je prends des nouvelles d'un scout malade ou absent",
  "J'aime les imprévus pendant un camp (météo, changement de programme)",
  "Je n'admets pas qu'on triche pendant un jeu ou une épreuve",
  "J'aime partir en randonnée ou en camp itinérant",
  "Je remonte le moral d'un jeune qui a le mal du pays au camp",
  "Je suis toujours à l'heure au rassemblement pour ne pas me faire remarquer",
  "Je suis souvent en désaccord avec les autres chefs sur l'organisation du camp",
  "On me trouve logique et rationnel dans l'organisation d'une activité",
  "Il faut respecter les horaires du programme de camp",
  "Je ne contredis jamais le chef de groupe ou l'aumônier",
  "J'aide un scout en difficulté sans qu'on me le demande",
  "Je sympathise facilement avec les scouts d'une autre unité",
  "Les absences aux réunions doivent être justifiées",
  "Avant une activité, je réfléchis à la méthode et au matériel nécessaire",
  "Je suis râleur quand le programme du camp ne me convient pas",
  "Je suis organisé dans la préparation de mes camps et activités",
  "Je repère facilement les défauts d'organisation d'un camp",
  "Je dis « oui » à une mission alors que je voulais dire « non »",
  "Je prête facilement mon matériel de camping",
  "Quand une idée d'activité me plaît, je le dis sans hésiter",
  "J'apprécie la discipline et le respect des règles du camp",
  "Quand je suis en colère pendant un camp, on m'entend",
  "Je porte souvent des appréciations sur la tenue ou l'attitude des scouts",
  "Face à un imprévu ou un échec d'activité, je réfléchis calmement",
  "Je préfère donner de mon temps pour encadrer que d'être encadré",
  "En cas d'incident pendant un camp, je garde ma présence d'esprit",
  "Quand il faut porter l'uniforme, j'ai tendance à m'habiller autrement",
  "J'accorde de l'importance à ce que les autres chefs pensent de mon encadrement",
  "Je n'aime pas partir en camp sans un programme bien planifié",
  "J'aime rassurer les scouts avant une activité qui les inquiète",
  "J'évite de prendre la responsabilité d'une activité risquée",
  "J'adore taquiner les autres chefs ou les scouts",
  "Je passe beaucoup de temps à aider un scout en difficulté",
  "Ce n'est pas acceptable de ne pas respecter son tour de garde ou de corvée",
  "Je prévois les conséquences de mes décisions avant une activité",
  "Je choque parfois par mes propos devant les autres chefs",
  "Je suis plutôt timide devant un groupe de scouts",
  "On me trouve enthousiaste pendant les activités de camp",
  "Je remets en question mes choix d'encadrement quand il le faut",
  "Quand je suis content d'une activité réussie, ça se voit",
  "Face à un problème d'organisation, je rassemble un maximum d'informations avant de décider",
  "J'aime la dérision pendant les veillées ou les jeux",
  "J'ai le souci de ne pas déranger les autres chefs avec mes demandes",
  "Je ne cache pas mes émotions devant mon équipe",
  "Il est intolérable de ne pas respecter le silence lors d'une veillée ou d'un temps spirituel",
  "J'ai l'esprit de contradiction face aux décisions du chef de groupe",
  "Ça ne me déplairait pas de partir en mission humanitaire scoute à l'étranger",
  "Je me fais petit devant le chef de groupe ou l'aumônier",
  "Il est dommage que certaines traditions scoutes se perdent",
  "Avec moi, les scouts ne s'ennuient jamais en activité",
  "Dans le doute, je sais me référer au livre du chef ou consulter un chef expérimenté",
  "Je suis réputé pour la férocité de mes remarques envers les autres chefs",
  "La loi scoute doit être respectée, même quand elle est exigeante",
  "On me dit que je suis trop indulgent avec les scouts",
  "J'essaie de ressembler au chef que mes propres chefs voulaient que je devienne",
  "J'ai toujours une histoire à raconter autour du feu de camp",
  "J'ai tendance à prendre sous mon aile le scout le plus fragile du groupe",
];

const APE_QUESTIONS: string[] = [
  "En cas d'imprévu lors d'une kermesse ou d'un événement, je garde mon sang-froid",
  "J'aime bien taquiner les autres parents ou moquer certaines décisions de l'école",
  "Je me laisse facilement influencer par l'avis des autres parents",
  "Je prends des nouvelles d'un parent ou d'un enfant malade",
  "J'aime les imprévus lors de l'organisation d'un événement scolaire",
  "Je n'admets pas qu'on triche sur les comptes de l'association",
  "J'aime beaucoup organiser ou participer aux sorties scolaires",
  "Je remonte le moral d'un parent découragé par l'organisation",
  "Je suis toujours à l'heure aux réunions pour ne pas me faire remarquer",
  "Je suis souvent en désaccord avec les autres parents ou la direction de l'école",
  "On me trouve logique et rationnel dans la gestion du budget de l'association",
  "Il faut respecter les délais pour préparer la kermesse ou la fête de l'école",
  "Je ne contredis jamais le directeur ou la présidente de l'association",
  "J'aide à l'organisation d'un événement sans qu'on me le demande",
  "Je sympathise facilement avec de nouveaux parents",
  "Les absences aux réunions de l'association doivent être justifiées",
  "Avant d'organiser un événement, je réfléchis à la méthode et à l'organisation nécessaire",
  "Je suis râleur quand les décisions de l'association ne me conviennent pas",
  "Je suis organisé dans la préparation des événements de l'association",
  "Je repère facilement les failles d'organisation d'un événement",
  "Je dis « oui » pour une mission dans l'association alors que je voulais dire « non »",
  "Je prête facilement mon matériel pour les événements de l'école",
  "Quand une idée me plaît, je le dis sans hésiter en réunion",
  "J'apprécie que les règles de l'association soient respectées",
  "Quand je suis en colère en réunion, on m'entend",
  "Je porte souvent des appréciations sur l'investissement des autres parents",
  "Face à un échec d'organisation, je réfléchis calmement",
  "Je préfère donner de mon temps à l'association que d'en recevoir",
  "En cas d'imprévu pendant un événement, je garde ma présence d'esprit",
  "Quand il faut respecter un dress code pour un événement, j'ai tendance à faire autrement",
  "J'accorde de l'importance à ce que les autres parents pensent de mon implication",
  "Je n'aime pas organiser un événement sans un planning bien défini",
  "J'aime rassurer les parents inquiets pour un événement",
  "J'évite de prendre la responsabilité d'un poste au bureau de l'association",
  "J'adore taquiner les autres membres du bureau",
  "Je passe beaucoup de temps à aider les autres parents dans l'organisation",
  "Ce n'est pas acceptable de ne pas respecter son tour lors d'une buvette ou d'un stand",
  "Je prévois les conséquences de mes décisions avant un événement",
  "Je choque parfois par mes propos en réunion",
  "Je suis plutôt timide devant un groupe de parents",
  "On me trouve enthousiaste pendant la préparation des événements",
  "Je remets en question mes idées quand il le faut",
  "Quand je suis content d'un événement réussi, ça se voit",
  "Face à un problème d'organisation, je rassemble le plus d'informations possible avant de décider",
  "J'aime la dérision pendant les réunions ou les soirées de l'association",
  "J'ai le souci de ne pas déranger les autres parents avec mes demandes",
  "Je ne cache pas mes émotions devant les autres parents",
  "Il est intolérable de ne pas respecter les règles de sécurité lors d'un événement",
  "J'ai l'esprit de contradiction face aux décisions du bureau",
  "Ça ne me déplairait pas de m'investir dans une cause caritative pour l'école",
  "Je me fais petit devant le directeur ou la présidente de l'association",
  "Il est dommage que certaines traditions de l'école se perdent",
  "Avec moi, les réunions ne sont jamais ennuyeuses",
  "Dans le doute, je sais me renseigner auprès du bureau ou des statuts de l'association",
  "Je suis réputé pour la férocité de mes remarques envers les autres parents",
  "Le règlement de l'association doit être respecté, même quand il est contraignant",
  "On me dit que je suis trop indulgent avec les autres parents",
  "J'essaie de m'investir comme mes propres parents l'auraient souhaité",
  "J'ai toujours une histoire à raconter lors des réunions",
  "J'ai tendance à prendre sous mon aile le parent le plus isolé du groupe",
];

export const QUESTION_VARIANTS: Record<QuestionVariantKey, string[]> = {
  default: DEFAULT_QUESTIONS,
  scouts: SCOUTS_QUESTIONS,
  ape: APE_QUESTIONS,
};

export function isQuestionVariantKey(v: unknown): v is QuestionVariantKey {
  return v === "default" || v === "scouts" || v === "ape";
}
