/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiPublicSaveResultRouteImport } from './routes/api/public/save-result'
import { Route as ApiPublicSaveContactRouteImport } from './routes/api/public/save-contact'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSaveResultRoute = ApiPublicSaveResultRouteImport.update({
  id: '/api/public/save-result',
  path: '/api/public/save-result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSaveContactRoute = ApiPublicSaveContactRouteImport.update({
  id: '/api/public/save-contact',
  path: '/api/public/save-contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/stats': typeof StatsRoute
  '/api/public/save-contact': typeof ApiPublicSaveContactRoute
  '/api/public/save-result': typeof ApiPublicSaveResultRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/stats': typeof StatsRoute
  '/api/public/save-contact': typeof ApiPublicSaveContactRoute
  '/api/public/save-result': typeof ApiPublicSaveResultRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/stats': typeof StatsRoute
  '/api/public/save-contact': typeof ApiPublicSaveContactRoute
  '/api/public/save-result': typeof ApiPublicSaveResultRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/stats'
    | '/api/public/save-contact'
    | '/api/public/save-result'
    | '/api/public/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/stats'
    | '/api/public/save-contact'
    | '/api/public/save-result'
    | '/api/public/track'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/stats'
    | '/api/public/save-contact'
    | '/api/public/save-result'
    | '/api/public/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  StatsRoute: typeof StatsRoute
  ApiPublicSaveContactRoute: typeof ApiPublicSaveContactRoute
  ApiPublicSaveResultRoute: typeof ApiPublicSaveResultRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/save-result': {
      id: '/api/public/save-result'
      path: '/api/public/save-result'
      fullPath: '/api/public/save-result'
      preLoaderRoute: typeof ApiPublicSaveResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/save-contact': {
      id: '/api/public/save-contact'
      path: '/api/public/save-contact'
      fullPath: '/api/public/save-contact'
      preLoaderRoute: typeof ApiPublicSaveContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  StatsRoute: StatsRoute,
  ApiPublicSaveContactRoute: ApiPublicSaveContactRoute,
  ApiPublicSaveResultRoute: ApiPublicSaveResultRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
